### ISSUE TITLE
Webicons on Opera

### ISSUE THREAD

**Issue by sthrs** [adamfairhead/webicons#11]
Sir,
Would you happen to know why webicons not Showing on Opera 12.14 http://hardwearshoes.net/__index.html ? Is there any specific code I'm missing?

**Comment by adamfairhead** [comment]
Opera passes the Modernizr Opera "svg" test, but appears to fall flat on its face when it comes to really rendering them. When you modify the html attribute in the inspector to "no-svg" instead of "svg", the pngs display just fine. 

Removing the border-radius makes them actually display (although that reveals a bunch of other rendering issues it seems to have).

Thankfully, Opera is moving over to Blink ( http://thenextweb.com/insider/2013/04/04/opera-confirms-it-will-follow-google-and-ditch-webkit-for-blink-as-part-of-its-commitment-to-chromium/ ) so these problems should go away soon enough.

Don't need to lose _too_ much sleep over it in the mean time: http://www.w3schools.com/browsers/browsers_opera.asp
